### ISSUE TITLE
Sensor.Incidents not updating

### ISSUE THREAD

**Issue by genaxx** [cyberjunky/home-assistant-brandweerrooster#16]
The sensor.Incidents sensor has been stuck since it updated to an incident back on 2nd Jan. Even after restarting HA the sensor hasn't reset back to its default state, nor has it updated to incidents which have happened between then and now.

**Comment by cyberjunky** [comment]
Can you check if there are more incidents sensors? Like sensor.incidents2 or something like that?
Else enable debug and restart to see whats going on in log (see end of document page)

**Comment by genaxx** [comment]
I'm only seeing 3 entities;
binary_sensor.duty
switch.incident_response
sensor.incidents

i'll enable debug and give an update.

**Comment by genaxx** [comment]
Here's the logs,

This is what the sensor.Incident Entity is saying;

State:
"Title of last incident"

State Attributes:
```
id: 53884
trigger: update
created_at: '2021-01-02T05:11:06.336+00:00'
message_to_speech_url: >-
  https://static.fireservicerota.co.uk/incidents/000/053/884/incident-text-to-speech
type: incident_alert
responder_mode: available_in_schedule_is_acknowledgment
can_respond_until: '2021-01-02T05:41:06.336+00:00'
friendly_name: Incidents
icon: 'mdi:fire-truck'
```

Log shows that it's also being restored;
`2021-01-11 18:58:22 DEBUG (MainThread) [homeassistant.components.fireservicerota.sensor] Restored entity 'Incidents' to:  #### AFA [####]`

[FSRdebug.txt](https://github.com/cyberjunky/home-assistant-fireservicerota/files/5797953/FSRdebug.txt)

**Comment by cyberjunky** [comment]
I see nothing strange in this log, the ping lines mean the websocket client is connected to the server and is awaiting new incidents.

**Comment by genaxx** [comment]
I've tried deleting the integration and re-adding it but no luck either

**Comment by cyberjunky** [comment]
If there is no new event received the incident sensor stays on what is was before. Restarts in between will keep the same state (it's saved and reloaded) What do you expect the sensor value to be?

**Comment by genaxx** [comment]
Would it not reset to some default state once the incident clears? At the moment it appears like that incident has been going on since the 2nd Jan as its still the current state. But it also missed some incidents that have happened after that one, e.g on the 4th and 7th.

**Comment by cyberjunky** [comment]
No updates, closing

**Comment by jtbmedia** [comment]
Hi Cyberjunky,

I have exactly the same problem. It only updated the incidents sensor once. When new incidents are coming they are not updated. I can see them in my brandweerrooster app.
