### ISSUE TITLE
Add request to blueprint

### ISSUE THREAD

**Issue by denperss** [cyberjunky/home-assistant-brandweerrooster#17]
Cannot add the following to the blueprint

Request: 
State to ex. Unlock a door, or garage door
State to only enable light at a specific time.
'
FIX 
State when cast devices is playing TTS get executed then all music stop and not playing again..

**Comment by filmgarage** [comment]
Time range has been added to the Text To Speech blueprint, can you check if that is working and useful?
And what about the light blueprint? Maybe it is better to have an option to only switch on when sun is down?

**Comment by denperss** [comment]
Hi... 

Ok, i will check that. 
- the light blueprint, i can only select light devices.. i connot select entities device. (Sonoff switch) 
-

**Comment by cyberjunky** [comment]
No recent activities, closed. Reopen or create new ticket if needed.

**Comment by denperss** [comment]
Correct, because i was waiting for help to get it to work with entities devices also ? :(
