### ISSUE TITLE
trigger @wrong vehicle 

### ISSUE THREAD

**Issue by FirefighterMikeStefan** [cyberjunky/home-assistant-brandweerrooster#18]
Hello,

I am a firefighter and work different firestations troughout the veiligheidsregio because of that I have multiple groups at brandweerrooster. At this moment my lighting wil turn on if there is a incident for a station I am linked to. but i want my lighting only to respond to the firehouse I have to respond to during the night and the weekend how can i get that done? is there a trigger I can set on vehicle number? my duty sensor will be switc  on only if I am available for the firestation I want to so that is working the right way.

**Comment by filmgarage** [comment]
The incident status will - most likely - contain the name or number of the vehicle that is being called. You should be able to create a data template in Home Assistant to make sure your lights will only switch on when a specific vehicle is called. The template should check if the incident *contains* a specific piece of text. Please share your result if you manage to get it working or let us know if you don't succeed...

**Comment by filmgarage** [comment]
I asked around on Discord and MagieMalone helped out. This would be the part of the automation code to trigger switching on the light only if a specific text is part of the incident status:
```
  trigger:
    platform: template
    value_template: "{{states('sensor.incidents') |regex_match('name_of_vehicle.+', ignorecase=False)}}"
```
You would simply have to replace `name_of_vehicle` with the piece of text you want to use as a trigger.

I will try and create a blueprint for this automation later.

**Comment by FirefighterMikeStefan** [comment]
I'll probably have time for this tonight and then try to program it. will let you know if it's working but I will have to wait for a new incident so that may take a while. also looking forward to your blueprint of this automation.

**Comment by filmgarage** [comment]
If the above example does not work, try the following:
```
  trigger:
    platform: template
    value_template: "{{states('sensor.incidents') |regex_search('name_of_vehicle.+', ignorecase=False)}}"
```

**Comment by filmgarage** [comment]
I can confirm that this works. If you want the lights to switch on every time the incident contains for example TS112, you would have to add the following:
```
  trigger:
    platform: template
    value_template: "{{states('sensor.incidents') |regex_search('TS112+', ignorecase=False)}}"
```
If you change to ignorecase=False obviously it ignores upper and lower case ;-)

You can easily create your own automation in the frontend of Home Assistant:

![Schermafbeelding 2021-02-10 om 00 54 19](https://user-images.githubusercontent.com/30559371/107444271-8e9f1e80-6b3a-11eb-83c8-2a26e4717e03.png)

Dutch translation for "Template" is "Sjabloon"

**Comment by FirefighterMikeStefan** [comment]
It’s working thank you for helping me out with this problem!
