### ISSUE TITLE
FSR integration HA Core errors.

### ISSUE THREAD

**Issue by AbeltjeNL** [cyberjunky/home-assistant-brandweerrooster#20]
Since i've updated to HA Core 2021.7.1 the FSR integration spams the core logs with the following message:

'2021-07-11 19:29:42 ERROR (Thread-3) [websocket] error from callback <bound method FireServiceRotaIncidents.__on_message of <pyfireservicerota.FireServiceRotaIncidents object at 0x7f8be9bf9790>>: __on_message() takes 2 positional arguments but 3 were given'.

Also got this error for one time:

'2021-07-11 19:26:44 ERROR (Thread-3) [websocket] error from callback <bound method FireServiceRotaIncidents.__on_open of <pyfireservicerota.FireServiceRotaIncidents object at 0x7f8be9bf9790>>: __on_open() takes 1 positional argument but 2 were given'.

Is there something i can do to fix these error messages or is there some coding issue?

I did reinstall the integration but this doesn't seem to fix the issue.

**Comment by cyberjunky** [comment]
https://github.com/home-assistant/core/pull/52807

**Comment by AbeltjeNL** [comment]
Thanks for your quick response! Let's hope FSR will work again in the near future.
