### ISSUE TITLE
HA Core error.

### ISSUE THREAD

**Issue by AbeltjeNL** [cyberjunky/home-assistant-brandweerrooster#21]
Also after the fix in core 2021.7.2 there are errors. Sensor.incidents is not updating.
I reinstalled the integration, rebooted HA but no dice.

Error from logs:

'ERROR (Thread-3) [websocket] error from callback <bound method FireServiceRotaIncidents.__on_close of <pyfireservicerota.FireServiceRotaIncidents object at 0x7f246bedbd90>>: __on_close() takes 3 positional arguments but 4 were given'

**Comment by cyberjunky** [comment]
Thanks for reporting, sorry for the left over bug...

**Comment by cyberjunky** [comment]
This should *hopefully* be fixed in 2021.7.3, just released.

**Comment by AbeltjeNL** [comment]
Will install and test when 2021.7.3 is in stable!

**Comment by AbeltjeNL** [comment]
Just updated to 2021.7.3 and everything seems to be working fine again. Thank you very much for the effort @cyberjunky!!

**Comment by AbeltjeNL** [comment]
It's fixed! Closing this issue.
