### ISSUE TITLE
FSR not working 

### ISSUE THREAD

**Issue by denperss** [cyberjunky/home-assistant-brandweerrooster#23]
Logger: websocket
Source: /usr/local/lib/python3.9/site-packages/websocket/_logging.py:65
First occurred: 11:22:30 AM (2 occurrences)
Last logged: 11:22:30 AM

error from callback <bound method FireServiceRotaIncidents.__on_open of <pyfireservicerota.FireServiceRotaIncidents object at 0x7f8abd46a0>>: __on_open() takes 1 positional argument but 2 were given
error from callback <bound method FireServiceRotaIncidents.__on_error of <pyfireservicerota.FireServiceRotaIncidents object at 0x7f8abd46a0>>: __on_error() takes 2 positional arguments but 3 were given

- Im running the latest vers..

**Comment by cyberjunky** [comment]
@denperss This problem was solved a long time ago, which HA version do you run exactly?
Do you use the builtin fireservicerota component or did you install it under custom_components?
I just tested on 2021.10.6 it works without issues.
