### ISSUE TITLE
Adding task ID supplied through the API to the incidents sensor

### ISSUE THREAD

**Issue by stmolenaar** [cyberjunky/home-assistant-brandweerrooster#24]
Would it be possible to add the task ID as supplied in the BRWR/ FSR API to the incident trigger?
This way users having access to multiple stations/ appliances can filter out appliances that do not count towards them.

**Comment by cyberjunky** [comment]
Hi Stefan, I will look into this!

**Comment by cyberjunky** [comment]
Hi @stmolenaar Is this ok? so task ids as attribute?

![image](https://user-images.githubusercontent.com/5447161/199083625-9f5c6952-7dcd-473c-8157-00d2f624c9fa.png)


I get no real incidents on Rob's test account anymore, so had to create some manually myself in the portal.

**Comment by stmolenaar** [comment]
Hi @cyberjunky ,

That is perfect, thank you!
If you want I can add a second appliance (task) and add some capcodes.
That way incident will come in automatically again and the difference between the appliances (tasks) will become visible.

Thanks already for the great help! This will make quite a few users happy.

**Comment by cyberjunky** [comment]
Change are included in home assistant 2022.11
